y=int(input())
if(y==1):print("One")
elif(y==2):print("Two")
elif(y==3):print("Three")
elif(y==4):print("Four")
elif(y==5):print("Five")
elif(y==6):print("Six")
elif(y==7):print("Seven")
elif(y==8):print("Eight")
elif(y==9):print("Nine")
else:print("Ten")

